openapi: 3.0.0
info:
  title: Blue Carbon Registry API
  version: 1.0.0
paths:
  /projects:
    get:
      summary: Get all projects
      responses:
        '200':
          description: List of projects
  /mint-credit:
    post:
      summary: Mint carbon credits
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
      responses:
        '200':
          description: Mint result
  /admin/projects:
    get:
      summary: Admin: Get all projects
      responses:
        '200':
          description: List of projects